export default {
    1: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/first.png'),
    2: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/second.png'),
    3: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/third.png'),
    4: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/fourth.png'),
    5: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/fifth.png'),
    6: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/sixth.png'),
    7: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/seventh.png'),
    8: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/eighth.png'),
    9: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/ninth.png'),
    10: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/tenth.png'),
    11: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/eleventh.png'),
    12: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/twelfth.png'),
    13: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/thirteenth.png'),
    14: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/fourteenth.png'),
    15: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/fifteenth.png'),
    16: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/sixteenth.png'),
    17: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/17th.png'),
    18: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/18th.png'),
    19: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/19th.png'),
    20: require('../IceFishObservatoryAssets/IsoberImagis/numberedFishesToCatch/20th.png'),
}